#!/bin/bash

# List of possible commit messages
commit_messages=(
  "Fix bug"
  "Add new feature"
  "Update documentation"
  "Refactor code"
  "Improve performance"
  "Fix typo"
  "Add tests"
)

# Generate a random number between 1 and 10
random_num=$(( RANDOM % 10 + 1 ))

# Check if the random number is greater than 1 (i.e. 90% chance of committing)
if [ $random_num -gt 1 ]; then
  # Choose a random number of commits to generate (between 1 and 10)
  num_commits=$(( RANDOM % 10 + 1 ))

  # Loop through and generate each commit
  for (( i=1; i<=$num_commits; i++ )); do
    # Choose a random commit message
    commit_message=${commit_messages[$RANDOM % ${#commit_messages[@]}]}

    # Generate a random file name and contents
    file_name="file$i.txt"
    random_string=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 20 | head -n 1)
    file_contents="This is a random file generated by the script for commit $i. $random_string"

    # Write the file to disk
    echo "$file_contents" > "$file_name"

    # Stage the file for commit
    git add "$file_name"

    # Commit the changes with the random commit message
    git commit -m "$commit_message"

  done

  # Push the changes to GitHub
  git push
else
  echo "No commits today"
fi
